name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies & Download Data
        run: |
          pip install flet gdown
          # 使用你提供的云盘ID下载必要文件
          gdown "https://drive.google.com/uc?id=1GudOlOQ5vIn7YKzkBl-J36U9kdXk2Avc" -O data.zip
          # 解压文件
          unzip -o data.zip
          
      - name: Build APK
        run: flet build apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Chatbot-Release-APK
          path: build/apk/**/*.apk
